const data = [
  {
    influencerId: '3775',
    name: 'goodlands',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '05301',
    email: 'Goodlands@qa.eam',
    createdAt: '2024-01-09T07:03:18.889Z',
    notes: 'Goodlands',
    additionalContacts: 'Public figure',
    phoneNumber: '931454545445',
    influencerType: 'Micro',
    totalFollowerCount: '0',
    location: 'india gujarat brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2024-01-09T07:03:18.889Z',
    tier: '2',
    socialMediaAccountId: '4091',
    accountHandle: 'tom.curise.581',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5534',
    brandId: 1,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'Rascal + Friends',
    colorCode: '#30BFAD',
    influencerCategoryId: '5562',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3775',
    name: 'goodlands',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '05301',
    email: 'Goodlands@qa.eam',
    createdAt: '2024-01-09T07:03:18.889Z',
    notes: 'Goodlands',
    additionalContacts: 'Public figure',
    phoneNumber: '931454545445',
    influencerType: 'Micro',
    totalFollowerCount: '0',
    location: 'india gujarat brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2024-01-09T07:03:18.889Z',
    tier: '2',
    socialMediaAccountId: '4091',
    accountHandle: 'tom.curise.581',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5535',
    brandId: 2,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'NOOD',
    colorCode: '#405C93',
    influencerCategoryId: '5562',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3775',
    name: 'goodlands',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '05301',
    email: 'Goodlands@qa.eam',
    createdAt: '2024-01-09T07:03:18.889Z',
    notes: 'Goodlands',
    additionalContacts: 'Public figure',
    phoneNumber: '931454545445',
    influencerType: 'Micro',
    totalFollowerCount: '0',
    location: 'india gujarat brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2024-01-09T07:03:18.889Z',
    tier: '2',
    socialMediaAccountId: '4091',
    accountHandle: 'tom.curise.581',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5536',
    brandId: 6,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'Millie Moon',
    colorCode: '#00263E',
    influencerCategoryId: '5562',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3775',
    name: 'goodlands',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '05301',
    email: 'Goodlands@qa.eam',
    createdAt: '2024-01-09T07:03:18.889Z',
    notes: 'Goodlands',
    additionalContacts: 'Public figure',
    phoneNumber: '931454545445',
    influencerType: 'Micro',
    totalFollowerCount: '0',
    location: 'india gujarat brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2024-01-09T07:03:18.889Z',
    tier: '2',
    socialMediaAccountId: '4091',
    accountHandle: 'tom.curise.581',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5537',
    brandId: 8,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'Bactive',
    colorCode: '#073A79',
    influencerCategoryId: '5562',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3775',
    name: 'goodlands',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '05301',
    email: 'Goodlands@qa.eam',
    createdAt: '2024-01-09T07:03:18.889Z',
    notes: 'Goodlands',
    additionalContacts: 'Public figure',
    phoneNumber: '931454545445',
    influencerType: 'Micro',
    totalFollowerCount: '0',
    location: 'india gujarat brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2024-01-09T07:03:18.889Z',
    tier: '2',
    socialMediaAccountId: '4091',
    accountHandle: 'tom.curise.581',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5538',
    brandId: 38,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'Bonkers',
    colorCode: '#FFC0CB',
    influencerCategoryId: '5562',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3775',
    name: 'goodlands',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '05301',
    email: 'Goodlands@qa.eam',
    createdAt: '2024-01-09T07:03:18.889Z',
    notes: 'Goodlands',
    additionalContacts: 'Public figure',
    phoneNumber: '931454545445',
    influencerType: 'Micro',
    totalFollowerCount: '0',
    location: 'india gujarat brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2024-01-09T07:03:18.889Z',
    tier: '2',
    socialMediaAccountId: '4091',
    accountHandle: 'tom.curise.581',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5533',
    brandId: 4,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: true,
    brandName: 'MONDAY',
    colorCode: '#E38F66',
    influencerCategoryId: '5562',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3775',
    name: 'goodlands',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '05301',
    email: 'Goodlands@qa.eam',
    createdAt: '2024-01-09T07:03:18.889Z',
    notes: 'Goodlands',
    additionalContacts: 'Public figure',
    phoneNumber: '931454545445',
    influencerType: 'Micro',
    totalFollowerCount: '0',
    location: 'india gujarat brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2024-01-09T07:03:18.889Z',
    tier: '2',
    socialMediaAccountId: '4091',
    accountHandle: 'tom.curise.581',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5534',
    brandId: 1,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'Rascal + Friends',
    colorCode: '#30BFAD',
    influencerCategoryId: '5563',
    categoryId: 8,
    categoryName: 'lifestyle'
  },
  {
    influencerId: '3775',
    name: 'goodlands',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '05301',
    email: 'Goodlands@qa.eam',
    createdAt: '2024-01-09T07:03:18.889Z',
    notes: 'Goodlands',
    additionalContacts: 'Public figure',
    phoneNumber: '931454545445',
    influencerType: 'Micro',
    totalFollowerCount: '0',
    location: 'india gujarat brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2024-01-09T07:03:18.889Z',
    tier: '2',
    socialMediaAccountId: '4091',
    accountHandle: 'tom.curise.581',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5535',
    brandId: 2,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'NOOD',
    colorCode: '#405C93',
    influencerCategoryId: '5563',
    categoryId: 8,
    categoryName: 'lifestyle'
  },
  {
    influencerId: '3775',
    name: 'goodlands',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '05301',
    email: 'Goodlands@qa.eam',
    createdAt: '2024-01-09T07:03:18.889Z',
    notes: 'Goodlands',
    additionalContacts: 'Public figure',
    phoneNumber: '931454545445',
    influencerType: 'Micro',
    totalFollowerCount: '0',
    location: 'india gujarat brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2024-01-09T07:03:18.889Z',
    tier: '2',
    socialMediaAccountId: '4091',
    accountHandle: 'tom.curise.581',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5536',
    brandId: 6,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'Millie Moon',
    colorCode: '#00263E',
    influencerCategoryId: '5563',
    categoryId: 8,
    categoryName: 'lifestyle'
  },
  {
    influencerId: '3775',
    name: 'goodlands',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '05301',
    email: 'Goodlands@qa.eam',
    createdAt: '2024-01-09T07:03:18.889Z',
    notes: 'Goodlands',
    additionalContacts: 'Public figure',
    phoneNumber: '931454545445',
    influencerType: 'Micro',
    totalFollowerCount: '0',
    location: 'india gujarat brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2024-01-09T07:03:18.889Z',
    tier: '2',
    socialMediaAccountId: '4091',
    accountHandle: 'tom.curise.581',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5537',
    brandId: 8,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'Bactive',
    colorCode: '#073A79',
    influencerCategoryId: '5563',
    categoryId: 8,
    categoryName: 'lifestyle'
  },
  {
    influencerId: '3775',
    name: 'goodlands',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '05301',
    email: 'Goodlands@qa.eam',
    createdAt: '2024-01-09T07:03:18.889Z',
    notes: 'Goodlands',
    additionalContacts: 'Public figure',
    phoneNumber: '931454545445',
    influencerType: 'Micro',
    totalFollowerCount: '0',
    location: 'india gujarat brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2024-01-09T07:03:18.889Z',
    tier: '2',
    socialMediaAccountId: '4091',
    accountHandle: 'tom.curise.581',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5538',
    brandId: 38,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'Bonkers',
    colorCode: '#FFC0CB',
    influencerCategoryId: '5563',
    categoryId: 8,
    categoryName: 'lifestyle'
  },
  {
    influencerId: '3775',
    name: 'goodlands',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '05301',
    email: 'Goodlands@qa.eam',
    createdAt: '2024-01-09T07:03:18.889Z',
    notes: 'Goodlands',
    additionalContacts: 'Public figure',
    phoneNumber: '931454545445',
    influencerType: 'Micro',
    totalFollowerCount: '0',
    location: 'india gujarat brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2024-01-09T07:03:18.889Z',
    tier: '2',
    socialMediaAccountId: '4091',
    accountHandle: 'tom.curise.581',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5533',
    brandId: 4,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: true,
    brandName: 'MONDAY',
    colorCode: '#E38F66',
    influencerCategoryId: '5563',
    categoryId: 8,
    categoryName: 'lifestyle'
  },
  {
    influencerId: '3773',
    name: 'dhrumil bhut',
    gender: 'MALE',
    address1: null,
    address2: null,
    city: null,
    state: null,
    country: 'INDIA',
    postalCode: null,
    email: null,
    createdAt: '2024-01-04T10:10:45.640Z',
    notes: null,
    additionalContacts: null,
    phoneNumber: null,
    influencerType: 'Nano',
    totalFollowerCount: '0',
    location: 'india  ',
    totalShipmentCount: null,
    createdBy: '3',
    creatorName: 'Priyank',
    updatedAt: '2024-01-04T10:10:45.640Z',
    tier: '1',
    socialMediaAccountId: '4089',
    accountHandle: 'dhrumil__bhut',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5521',
    brandId: 4,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'MONDAY',
    colorCode: '#E38F66',
    influencerCategoryId: '5558',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3773',
    name: 'dhrumil bhut',
    gender: 'MALE',
    address1: null,
    address2: null,
    city: null,
    state: null,
    country: 'INDIA',
    postalCode: null,
    email: null,
    createdAt: '2024-01-04T10:10:45.640Z',
    notes: null,
    additionalContacts: null,
    phoneNumber: null,
    influencerType: 'Nano',
    totalFollowerCount: '0',
    location: 'india  ',
    totalShipmentCount: null,
    createdBy: '3',
    creatorName: 'Priyank',
    updatedAt: '2024-01-04T10:10:45.640Z',
    tier: '1',
    socialMediaAccountId: '4089',
    accountHandle: 'dhrumil__bhut',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5521',
    brandId: 4,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'MONDAY',
    colorCode: '#E38F66',
    influencerCategoryId: '5559',
    categoryId: 8,
    categoryName: 'lifestyle'
  },
  {
    influencerId: '3773',
    name: 'dhrumil bhut',
    gender: 'MALE',
    address1: null,
    address2: null,
    city: null,
    state: null,
    country: 'INDIA',
    postalCode: null,
    email: null,
    createdAt: '2024-01-04T10:10:45.640Z',
    notes: null,
    additionalContacts: null,
    phoneNumber: null,
    influencerType: 'Nano',
    totalFollowerCount: '0',
    location: 'india  ',
    totalShipmentCount: null,
    createdBy: '3',
    creatorName: 'Priyank',
    updatedAt: '2024-01-04T10:10:45.640Z',
    tier: '1',
    socialMediaAccountId: '4089',
    accountHandle: 'dhrumil__bhut',
    platform: 'INSTAGRAM',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5521',
    brandId: 4,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'MONDAY',
    colorCode: '#E38F66',
    influencerCategoryId: '5561',
    categoryId: 216,
    categoryName: 'zuru_test'
  },
  {
    influencerId: '3772',
    name: "charli d' amelio",
    gender: null,
    address1: null,
    address2: null,
    city: null,
    state: null,
    country: 'INDIA',
    postalCode: null,
    email: 'CHARLI@qa.team',
    createdAt: '2024-01-02T12:40:18.216Z',
    notes: null,
    additionalContacts: null,
    phoneNumber: null,
    influencerType: 'Mega',
    totalFollowerCount: '0',
    location: 'india  ',
    totalShipmentCount: null,
    createdBy: '119',
    creatorName: 'Vishal Rathod',
    updatedAt: '2024-01-02T12:40:18.216Z',
    tier: '1',
    socialMediaAccountId: '4088',
    accountHandle: 'spencerx',
    platform: 'TIKTOK',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5519',
    brandId: 4,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: true,
    brandName: 'MONDAY',
    colorCode: '#E38F66',
    influencerCategoryId: '5556',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3772',
    name: "charli d' amelio",
    gender: null,
    address1: null,
    address2: null,
    city: null,
    state: null,
    country: 'INDIA',
    postalCode: null,
    email: 'CHARLI@qa.team',
    createdAt: '2024-01-02T12:40:18.216Z',
    notes: null,
    additionalContacts: null,
    phoneNumber: null,
    influencerType: 'Mega',
    totalFollowerCount: '0',
    location: 'india  ',
    totalShipmentCount: null,
    createdBy: '119',
    creatorName: 'Vishal Rathod',
    updatedAt: '2024-01-02T12:40:18.216Z',
    tier: '1',
    socialMediaAccountId: '4088',
    accountHandle: 'spencerx',
    platform: 'TIKTOK',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5528',
    brandId: 3,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'Dose',
    colorCode: '#0B5C8F',
    influencerCategoryId: '5556',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3772',
    name: "charli d' amelio",
    gender: null,
    address1: null,
    address2: null,
    city: null,
    state: null,
    country: 'INDIA',
    postalCode: null,
    email: 'CHARLI@qa.team',
    createdAt: '2024-01-02T12:40:18.216Z',
    notes: null,
    additionalContacts: null,
    phoneNumber: null,
    influencerType: 'Mega',
    totalFollowerCount: '0',
    location: 'india  ',
    totalShipmentCount: null,
    createdBy: '119',
    creatorName: 'Vishal Rathod',
    updatedAt: '2024-01-02T12:40:18.216Z',
    tier: '1',
    socialMediaAccountId: '4088',
    accountHandle: 'spencerx',
    platform: 'TIKTOK',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5519',
    brandId: 4,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: true,
    brandName: 'MONDAY',
    colorCode: '#E38F66',
    influencerCategoryId: '5557',
    categoryId: 8,
    categoryName: 'lifestyle'
  },
  {
    influencerId: '3772',
    name: "charli d' amelio",
    gender: null,
    address1: null,
    address2: null,
    city: null,
    state: null,
    country: 'INDIA',
    postalCode: null,
    email: 'CHARLI@qa.team',
    createdAt: '2024-01-02T12:40:18.216Z',
    notes: null,
    additionalContacts: null,
    phoneNumber: null,
    influencerType: 'Mega',
    totalFollowerCount: '0',
    location: 'india  ',
    totalShipmentCount: null,
    createdBy: '119',
    creatorName: 'Vishal Rathod',
    updatedAt: '2024-01-02T12:40:18.216Z',
    tier: '1',
    socialMediaAccountId: '4088',
    accountHandle: 'spencerx',
    platform: 'TIKTOK',
    newFollowerCount: '0',
    fbConnected: false,
    influencerBrandId: '5528',
    brandId: 3,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'Dose',
    colorCode: '#0B5C8F',
    influencerCategoryId: '5557',
    categoryId: 8,
    categoryName: 'lifestyle'
  },
  {
    influencerId: '3769',
    name: 'bruna marquezine',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Brasília',
    country: 'BRAZIL',
    postalCode: '989898',
    email: 'brunamarquezine@qa.team',
    createdAt: '2023-12-28T06:17:01.376Z',
    notes: "As of my last knowledge update in January 2022, I don't have real-time access to specific Instagram account rankings. Influencer popularity can change over time, and the number of followers may vary.\n" +
      '\n' +
      'However, here are ten popular Brazilian influencers on Instagram who were well-known as of my last update. Keep in mind that their follower counts may have changed:',
    additionalContacts: 'Public figure',
    phoneNumber: '5598989885512',
    influencerType: 'Micro',
    totalFollowerCount: '45285007',
    location: 'brazil brasília brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2023-12-28T07:09:10.432Z',
    tier: '2',
    socialMediaAccountId: '4085',
    accountHandle: 'brunamarquezine',
    platform: 'INSTAGRAM',
    newFollowerCount: '45285007',
    fbConnected: false,
    influencerBrandId: '5511',
    brandId: 2,
    brandContactStatus: 'CONTACT_MADE',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'NOOD',
    colorCode: '#405C93',
    influencerCategoryId: '5554',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3769',
    name: 'bruna marquezine',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Brasília',
    country: 'BRAZIL',
    postalCode: '989898',
    email: 'brunamarquezine@qa.team',
    createdAt: '2023-12-28T06:17:01.376Z',
    notes: "As of my last knowledge update in January 2022, I don't have real-time access to specific Instagram account rankings. Influencer popularity can change over time, and the number of followers may vary.\n" +
      '\n' +
      'However, here are ten popular Brazilian influencers on Instagram who were well-known as of my last update. Keep in mind that their follower counts may have changed:',
    additionalContacts: 'Public figure',
    phoneNumber: '5598989885512',
    influencerType: 'Micro',
    totalFollowerCount: '45285007',
    location: 'brazil brasília brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2023-12-28T07:09:10.432Z',
    tier: '2',
    socialMediaAccountId: '4085',
    accountHandle: 'brunamarquezine',
    platform: 'INSTAGRAM',
    newFollowerCount: '45285007',
    fbConnected: false,
    influencerBrandId: '5512',
    brandId: 3,
    brandContactStatus: 'TO_CONTACT',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'Dose',
    colorCode: '#0B5C8F',
    influencerCategoryId: '5554',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3769',
    name: 'bruna marquezine',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Brasília',
    country: 'BRAZIL',
    postalCode: '989898',
    email: 'brunamarquezine@qa.team',
    createdAt: '2023-12-28T06:17:01.376Z',
    notes: "As of my last knowledge update in January 2022, I don't have real-time access to specific Instagram account rankings. Influencer popularity can change over time, and the number of followers may vary.\n" +
      '\n' +
      'However, here are ten popular Brazilian influencers on Instagram who were well-known as of my last update. Keep in mind that their follower counts may have changed:',
    additionalContacts: 'Public figure',
    phoneNumber: '5598989885512',
    influencerType: 'Micro',
    totalFollowerCount: '45285007',
    location: 'brazil brasília brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2023-12-28T07:09:10.432Z',
    tier: '2',
    socialMediaAccountId: '4085',
    accountHandle: 'brunamarquezine',
    platform: 'INSTAGRAM',
    newFollowerCount: '45285007',
    fbConnected: false,
    influencerBrandId: '5522',
    brandId: 6,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'Millie Moon',
    colorCode: '#00263E',
    influencerCategoryId: '5554',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3769',
    name: 'bruna marquezine',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Brasília',
    country: 'BRAZIL',
    postalCode: '989898',
    email: 'brunamarquezine@qa.team',
    createdAt: '2023-12-28T06:17:01.376Z',
    notes: "As of my last knowledge update in January 2022, I don't have real-time access to specific Instagram account rankings. Influencer popularity can change over time, and the number of followers may vary.\n" +
      '\n' +
      'However, here are ten popular Brazilian influencers on Instagram who were well-known as of my last update. Keep in mind that their follower counts may have changed:',
    additionalContacts: 'Public figure',
    phoneNumber: '5598989885512',
    influencerType: 'Micro',
    totalFollowerCount: '45285007',
    location: 'brazil brasília brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2023-12-28T07:09:10.432Z',
    tier: '2',
    socialMediaAccountId: '4085',
    accountHandle: 'brunamarquezine',
    platform: 'INSTAGRAM',
    newFollowerCount: '45285007',
    fbConnected: false,
    influencerBrandId: '5518',
    brandId: 4,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'MONDAY',
    colorCode: '#E38F66',
    influencerCategoryId: '5554',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3769',
    name: 'bruna marquezine',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Brasília',
    country: 'BRAZIL',
    postalCode: '989898',
    email: 'brunamarquezine@qa.team',
    createdAt: '2023-12-28T06:17:01.376Z',
    notes: "As of my last knowledge update in January 2022, I don't have real-time access to specific Instagram account rankings. Influencer popularity can change over time, and the number of followers may vary.\n" +
      '\n' +
      'However, here are ten popular Brazilian influencers on Instagram who were well-known as of my last update. Keep in mind that their follower counts may have changed:',
    additionalContacts: 'Public figure',
    phoneNumber: '5598989885512',
    influencerType: 'Micro',
    totalFollowerCount: '45285007',
    location: 'brazil brasília brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2023-12-28T07:09:10.432Z',
    tier: '2',
    socialMediaAccountId: '4085',
    accountHandle: 'brunamarquezine',
    platform: 'INSTAGRAM',
    newFollowerCount: '45285007',
    fbConnected: false,
    influencerBrandId: '5511',
    brandId: 2,
    brandContactStatus: 'CONTACT_MADE',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'NOOD',
    colorCode: '#405C93',
    influencerCategoryId: '5555',
    categoryId: 8,
    categoryName: 'lifestyle'
  },
  {
    influencerId: '3769',
    name: 'bruna marquezine',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Brasília',
    country: 'BRAZIL',
    postalCode: '989898',
    email: 'brunamarquezine@qa.team',
    createdAt: '2023-12-28T06:17:01.376Z',
    notes: "As of my last knowledge update in January 2022, I don't have real-time access to specific Instagram account rankings. Influencer popularity can change over time, and the number of followers may vary.\n" +
      '\n' +
      'However, here are ten popular Brazilian influencers on Instagram who were well-known as of my last update. Keep in mind that their follower counts may have changed:',
    additionalContacts: 'Public figure',
    phoneNumber: '5598989885512',
    influencerType: 'Micro',
    totalFollowerCount: '45285007',
    location: 'brazil brasília brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2023-12-28T07:09:10.432Z',
    tier: '2',
    socialMediaAccountId: '4085',
    accountHandle: 'brunamarquezine',
    platform: 'INSTAGRAM',
    newFollowerCount: '45285007',
    fbConnected: false,
    influencerBrandId: '5512',
    brandId: 3,
    brandContactStatus: 'TO_CONTACT',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'Dose',
    colorCode: '#0B5C8F',
    influencerCategoryId: '5555',
    categoryId: 8,
    categoryName: 'lifestyle'
  },
  {
    influencerId: '3769',
    name: 'bruna marquezine',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Brasília',
    country: 'BRAZIL',
    postalCode: '989898',
    email: 'brunamarquezine@qa.team',
    createdAt: '2023-12-28T06:17:01.376Z',
    notes: "As of my last knowledge update in January 2022, I don't have real-time access to specific Instagram account rankings. Influencer popularity can change over time, and the number of followers may vary.\n" +
      '\n' +
      'However, here are ten popular Brazilian influencers on Instagram who were well-known as of my last update. Keep in mind that their follower counts may have changed:',
    additionalContacts: 'Public figure',
    phoneNumber: '5598989885512',
    influencerType: 'Micro',
    totalFollowerCount: '45285007',
    location: 'brazil brasília brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2023-12-28T07:09:10.432Z',
    tier: '2',
    socialMediaAccountId: '4085',
    accountHandle: 'brunamarquezine',
    platform: 'INSTAGRAM',
    newFollowerCount: '45285007',
    fbConnected: false,
    influencerBrandId: '5522',
    brandId: 6,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'Millie Moon',
    colorCode: '#00263E',
    influencerCategoryId: '5555',
    categoryId: 8,
    categoryName: 'lifestyle'
  },
  {
    influencerId: '3769',
    name: 'bruna marquezine',
    gender: 'MALE',
    address1: '1990',
    address2: 'Buck Drive',
    city: 'Brattleboro',
    state: 'Brasília',
    country: 'BRAZIL',
    postalCode: '989898',
    email: 'brunamarquezine@qa.team',
    createdAt: '2023-12-28T06:17:01.376Z',
    notes: "As of my last knowledge update in January 2022, I don't have real-time access to specific Instagram account rankings. Influencer popularity can change over time, and the number of followers may vary.\n" +
      '\n' +
      'However, here are ten popular Brazilian influencers on Instagram who were well-known as of my last update. Keep in mind that their follower counts may have changed:',
    additionalContacts: 'Public figure',
    phoneNumber: '5598989885512',
    influencerType: 'Micro',
    totalFollowerCount: '45285007',
    location: 'brazil brasília brattleboro',
    totalShipmentCount: null,
    createdBy: '111',
    creatorName: 'Akshay',
    updatedAt: '2023-12-28T07:09:10.432Z',
    tier: '2',
    socialMediaAccountId: '4085',
    accountHandle: 'brunamarquezine',
    platform: 'INSTAGRAM',
    newFollowerCount: '45285007',
    fbConnected: false,
    influencerBrandId: '5518',
    brandId: 4,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'MONDAY',
    colorCode: '#E38F66',
    influencerCategoryId: '5555',
    categoryId: 8,
    categoryName: 'lifestyle'
  },
  {
    influencerId: '3768',
    name: 'parth solanki',
    gender: 'MALE',
    address1: null,
    address2: 'hdh',
    city: 'ahmedanad',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '380015',
    email: 'animation.parth@gmail.com',
    createdAt: '2023-12-27T12:47:33.856Z',
    notes: null,
    additionalContacts: null,
    phoneNumber: '918866156849',
    influencerType: 'Nano',
    totalFollowerCount: '10607',
    location: 'india gujarat ahmedanad',
    totalShipmentCount: null,
    createdBy: '3',
    creatorName: 'Priyank',
    updatedAt: '2024-01-08T10:26:07.815Z',
    tier: '1',
    socialMediaAccountId: '4084',
    accountHandle: 'parth_solanki_97',
    platform: 'INSTAGRAM',
    newFollowerCount: '10607',
    fbConnected: false,
    influencerBrandId: '5508',
    brandId: 30,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'ZURU Tech India',
    colorCode: '#FFDAB9',
    influencerCategoryId: '5549',
    categoryId: 7,
    categoryName: 'fashion'
  },
  {
    influencerId: '3768',
    name: 'parth solanki',
    gender: 'MALE',
    address1: null,
    address2: 'hdh',
    city: 'ahmedanad',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '380015',
    email: 'animation.parth@gmail.com',
    createdAt: '2023-12-27T12:47:33.856Z',
    notes: null,
    additionalContacts: null,
    phoneNumber: '918866156849',
    influencerType: 'Nano',
    totalFollowerCount: '10607',
    location: 'india gujarat ahmedanad',
    totalShipmentCount: null,
    createdBy: '3',
    creatorName: 'Priyank',
    updatedAt: '2024-01-08T10:26:07.815Z',
    tier: '1',
    socialMediaAccountId: '4084',
    accountHandle: 'parth_solanki_97',
    platform: 'INSTAGRAM',
    newFollowerCount: '10607',
    fbConnected: false,
    influencerBrandId: '5509',
    brandId: 4,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: true,
    brandName: 'MONDAY',
    colorCode: '#E38F66',
    influencerCategoryId: '5549',
    categoryId: 7,
    categoryName: 'fashion'
  },
  {
    influencerId: '3768',
    name: 'parth solanki',
    gender: 'MALE',
    address1: null,
    address2: 'hdh',
    city: 'ahmedanad',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '380015',
    email: 'animation.parth@gmail.com',
    createdAt: '2023-12-27T12:47:33.856Z',
    notes: null,
    additionalContacts: null,
    phoneNumber: '918866156849',
    influencerType: 'Nano',
    totalFollowerCount: '10607',
    location: 'india gujarat ahmedanad',
    totalShipmentCount: null,
    createdBy: '3',
    creatorName: 'Priyank',
    updatedAt: '2024-01-08T10:26:07.815Z',
    tier: '1',
    socialMediaAccountId: '4084',
    accountHandle: 'parth_solanki_97',
    platform: 'INSTAGRAM',
    newFollowerCount: '10607',
    fbConnected: false,
    influencerBrandId: '5508',
    brandId: 30,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'ZURU Tech India',
    colorCode: '#FFDAB9',
    influencerCategoryId: '5550',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3768',
    name: 'parth solanki',
    gender: 'MALE',
    address1: null,
    address2: 'hdh',
    city: 'ahmedanad',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '380015',
    email: 'animation.parth@gmail.com',
    createdAt: '2023-12-27T12:47:33.856Z',
    notes: null,
    additionalContacts: null,
    phoneNumber: '918866156849',
    influencerType: 'Nano',
    totalFollowerCount: '10607',
    location: 'india gujarat ahmedanad',
    totalShipmentCount: null,
    createdBy: '3',
    creatorName: 'Priyank',
    updatedAt: '2024-01-08T10:26:07.815Z',
    tier: '1',
    socialMediaAccountId: '4084',
    accountHandle: 'parth_solanki_97',
    platform: 'INSTAGRAM',
    newFollowerCount: '10607',
    fbConnected: false,
    influencerBrandId: '5509',
    brandId: 4,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: true,
    brandName: 'MONDAY',
    colorCode: '#E38F66',
    influencerCategoryId: '5550',
    categoryId: 5,
    categoryName: 'fitness'
  },
  {
    influencerId: '3768',
    name: 'parth solanki',
    gender: 'MALE',
    address1: null,
    address2: 'hdh',
    city: 'ahmedanad',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '380015',
    email: 'animation.parth@gmail.com',
    createdAt: '2023-12-27T12:47:33.856Z',
    notes: null,
    additionalContacts: null,
    phoneNumber: '918866156849',
    influencerType: 'Nano',
    totalFollowerCount: '10607',
    location: 'india gujarat ahmedanad',
    totalShipmentCount: null,
    createdBy: '3',
    creatorName: 'Priyank',
    updatedAt: '2024-01-08T10:26:07.815Z',
    tier: '1',
    socialMediaAccountId: '4084',
    accountHandle: 'parth_solanki_97',
    platform: 'INSTAGRAM',
    newFollowerCount: '10607',
    fbConnected: false,
    influencerBrandId: '5508',
    brandId: 30,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: false,
    brandName: 'ZURU Tech India',
    colorCode: '#FFDAB9',
    influencerCategoryId: '5551',
    categoryId: 8,
    categoryName: 'lifestyle'
  },
  {
    influencerId: '3768',
    name: 'parth solanki',
    gender: 'MALE',
    address1: null,
    address2: 'hdh',
    city: 'ahmedanad',
    state: 'Gujarat',
    country: 'INDIA',
    postalCode: '380015',
    email: 'animation.parth@gmail.com',
    createdAt: '2023-12-27T12:47:33.856Z',
    notes: null,
    additionalContacts: null,
    phoneNumber: '918866156849',
    influencerType: 'Nano',
    totalFollowerCount: '10607',
    location: 'india gujarat ahmedanad',
    totalShipmentCount: null,
    createdBy: '3',
    creatorName: 'Priyank',
    updatedAt: '2024-01-08T10:26:07.815Z',
    tier: '1',
    socialMediaAccountId: '4084',
    accountHandle: 'parth_solanki_97',
    platform: 'INSTAGRAM',
    newFollowerCount: '10607',
    fbConnected: false,
    influencerBrandId: '5509',
    brandId: 4,
    brandContactStatus: 'NEW',
    influencerStatus: 'APPROVED',
    isPaid: true,
    brandName: 'MONDAY',
    colorCode: '#E38F66',
    influencerCategoryId: '5551',
    categoryId: 8,
    categoryName: 'lifestyle'
  }
]

module.exports = data;